### ISSUE TITLE
[FEATURE] [BREAKING] Transition Streaming Framework and Plugin to Scala

### ISSUE THREAD

**Issue by s-vitaliy** [SneaksAndData/arcane-framework-scala#75]
### Description

.NET has served its purpose and with the new design on the road that allows having both producer and consumer inside Arcane runner, we need Iceberg API access, which is not a thing in .NET. Thus we now depart from MS world and re-write streaming code in ZIO

### Checklist
- [x] Implement Change Capture interval
- [x] StreamGraphBuilder for backfills
- [x] Parse datetime correctly, see: https://learn.microsoft.com/en-us/power-apps/maker/data-platform/export-data-lake-faq
    - [x] Open question: timzone? 
- [ ] Logs and metrics: SneaksAndData/arcane-stream-sqlserver-change-tracking#98 
  - [x] enrich logs with stream id
  - [x] enrich logs with stream kind
  - ~[ ] remove logback.xml from arcane.framework~
  - [ ] snake_case for stream id and stream kind enrichers
  - [ ] Implement SneaksAndData/arcane-stream-sqlserver-change-tracking#87
- [x] SneaksAndData/arcane-stream-sqlserver-change-tracking#94
- [x] Refactor query provider based on comments in SneaksAndData/arcane-stream-sqlserver-change-tracking#75 
- [x] Update CRD model https://github.com/SneaksAndData/arcane-stream-sqlserver-change-tracking/issues/78
- [x] ~Group environment vairables consumed by the pulgin/framework~ it is not needed, for list we can use `.env` files, common file for all env variable names is actually not required.
- [ ] Implement implicit conversions using the `Conversion` typeclass as it is [implemented here](https://github.com/SneaksAndData/arcane-stream-sqlserver-change-tracking/blob/9e323ed6e240a3202040edec6602f37b0fc42fb4/plugin/arcane-stream-sqlserver-change-tracking/src/main/scala/models/app/StreamSpec.scala#L57)
- [ ] Tests enhancements:
    - [ ] Validate that the `getChanges` method actually moves forward in version history. see also: https://github.com/SneaksAndData/arcane-stream-sqlserver-change-tracking/pull/75#discussion_r1829095623
    - [ ] Add tests for exceptions
    - [ ] Add negative test cases to tests:
        - [ ] "QueryProvider" should "generate backfill query
        - [ ] "QueryProvider" should "generate schema query"
        - [ ] "QueryProvider" should "generate columns query"
- [ ] Refactor StreamGraphBuilder based on comments from https://github.com/SneaksAndData/arcane-stream-sqlserver-change-tracking/pull/77#discussion_r1832370269
- [ ] The `VersionedBatch` type should be abstract
- [ ] The `QueryRunner` class should be deleted
- [ ] Add license header to scala code files, see: [jetbrains docs](https://www.jetbrains.com/help/go/copyright.html#assign-profile-to-scope) and [examples in nexus](https://github.com/SneaksAndData/nexus-configuration-controller/pull/9)
- [ ] Code format check in CI
- [ ] Align java & openjdk & jre & scala versions in all infrastructure.
- [ ] Stream hooks in graph events
